language: java
jdk: oraclejdk9
cache:
  directories:
    - "$HOME/.m2"
notifications:
  email:
    recipients:
      - demkozlov@yandex.ru
    on_success: always
    on_failure: always

addons:
  sonarcloud:
    organization: demid5
    token:
      secure: GN7tKPZh9W+KIwNrKRHLLZBpy74HujvwFMS23xJJBCoVDN/4n0ngMXe0hcgNJ+4xSrg70TcKYqvHfWYF5ohJJuDbVPnY9jKQwT2rDgzY5j9+6m00qG5FKoPS+Xat9dhwgBtD9jJ7UsP07c2m9wAxXrjB20gNAWcIPGY7krOwdeI0jHgnooEZHd9AtwlXVDMYN83q3blYIP0TifVyggwaYKtuLKi1zs3gMrDWA7SYCgkUcv2nRGgBICsB7gHK6axGMwNUa2SCvfKbpa5BwyMMhDjGvt4YTba3KAq5WSjBugCrrk8wmg6e1SmUvNtbhdvCTT/v66USq7xZ56Eumz8j7JOH954iYcD2S58Sz1rApDCNSpcpbH4fFsjmhTaEohEU7wrwaTcXt9S8sD/B8ms58cSlpC2COss31HVYJ2nbLcnf+Y/Q7R0jSW217e13QFtsmxc+dtOw394786Likobg6BUFVCTiGAc8LNvuhAQS2AZOJv3Y3AngqwiI9++leusyGeLDOZUK5MojECvNhp/ejXIWjrvmXNGrla9zeN8z7rgBBx7tUTLHkni7k/czVSAdh/J6GRihnOVsjTV9MlU4cw7ZuqbLrU5T3TrUFKXrR2Ufw94Ne/HOeAv/8NbGmIkjRintXXoaX+bM1QCkbB3g6ywKC3YHk3l5aI6qsCZpf58=